name: test
on: [push]
jobs:
  test:
    name: Test haskell codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        id: haskell-setup
        with:
          ghc-version: "8.8.3"
          enable-stack: true
          stack-version: "2.5.1"
      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            ${{steps.haskell-setup.outputs.stack-path}}
            ~/.stack
            ./.stack-work/
          key: ${{ runner.os }}-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/onix.cabal') }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: ls -lah ${{steps.haskell-setup.outputs.stack-path}}
      - run: make test
  e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: npm install
      - run: npx bazelisk test //e2e/go:snapshot_test
